#!/bin/bash

gcc -Wall -pedantic -Werror -Wextra -std=gnu89 ./tests/0-main.c 0-hash_table_create.c -o ./builds/create_hash

if [ "$?" = "0" ];
then
    ./builds/create_hash

    valgrind ./builds/create_hash

    echo -e "Test Completed, Cleaning up...\n"

    rm -v ./builds/create_hash
else
    echo -e "Build Failed!!!\n"
fi
