#!/bin/bash

gcc -Wall -pedantic -Werror -Wextra -std=gnu89 ./tests/6-main.c *.c -o ./builds/delete

if [ "$?" = "0" ];
then
    ./builds/delete

    valgrind ./builds/delete

    echo -e "Test Completed, Cleaning up...\n"

    rm -v ./builds/delete
else
    echo -e "Build Failed!!!\n"
fi
